### PR TITLE
Feature/ztc new required fields

### PR DESCRIPTION
**Pull request by annashamray**
Depends on https://github.com/VNG-Realisatie/gemma-postman-tests/pull/36

### CODE REVIEW

**Comment by michielverhoef** [comment]
@annashamray thank you for this PR. When I try to run ZGW_api_postman_test.json I get errors. Although I think the changes look good I am hesitating to approve the PR.  Could it be that these cnages were made on an older version of the Postman scripts?

**Comment by annashamray** [comment]
@michielverhoef Yes. it's possible
I've created several PRs in this lib which are chained (each one depends on the previous PR):
* https://github.com/VNG-Realisatie/gemma-postman-tests/pull/33 - support the required unlocking of documents in Documenten API before deleting them
* https://github.com/VNG-Realisatie/gemma-postman-tests/pull/34 - use non-superuser tokens  in Catalogi API to support `geforceerd-schrijven` claim
* https://github.com/VNG-Realisatie/gemma-postman-tests/pull/35 - remove test, which checks that Document.informatieobjecttype is immutable, since this restriction was removed
* https://github.com/VNG-Realisatie/gemma-postman-tests/pull/36 - remove ordering Zaken on "identificatie", but this PR looks redundant, since ordering on `identificatie` is supported now
* This PR, which adds required `InformatieObjectType.informatieobjectcategorie` in POST requests in Catalogi API

I see that the Postman tests were changed after the first of these PRs was open and now there are conflicts in changes. Could you please take a look, if these changes are already supported in Postman tests. If they are supported feel free to close my PRs. If not could you please resolve conflicts and review my PRs?

**Comment by joeribekker** [comment]
@michielverhoef I think updating the postman tests should have the highest priority, as they make it possible to test API implementations.

@annashamray let's focus our efforts on the API and until then use a fork of the postman tests for sanity reasons, or disable the tests. I think it's VNGs task to update these tests. Otherwise we're validating our implementation against our own tests, which is a little weird.

**Comment by annashamray** [comment]
@joeribekker Sure, I'll close this PR then

**Pull request closed without merging**
